matrix:
  include:
    - os: linux
      dist: bionic
      sudo: required
      language: generic
      python: "3.5"
      cache: pip

      before_install:
        # - sudo apt install python3-pip
        - sudo apt install pyqt5-dev-tools
        # - sudo pip3 install -r requirements.txt       

script:
  - echo "Yeet"
  - exit 0
