# vim: set ts=2 et:

# run xvfb with 32-bit color
# xvfb-run -s '-screen 0 1600x1200x24+32' command_goes_here

matrix:
  include:

    # Python 3 + QT5
    - os: linux
      dist: bionic
      sudo: required
      language: generic
      python: "3.5"
      env:
        - QT=5
        - CONDA=4.2.0
      addons:
        apt:
          packages:
            - cmake
            - xvfb
      before_install:
        - curl -O https://repo.continuum.io/archive/Anaconda3-4.2.0-Linux-x86_64.sh
        - /bin/bash Anaconda3-4.2.0-Linux-x86_64.sh -b -p $HOME/anaconda3
        - export PATH="$HOME/anaconda3/bin:$PATH"
        - conda create -y -n myqlanet-py3qt5 python=3.5
        - source activate myqlanet-py3qt5
        - conda install -y pyqt=5
        - conda install -y lxml
        - make qt5py3
        - xvfb-run make testpy3

script:
  - exit 0
