matrix:
  include:
    - os: linux
      dist: focal
      sudo: required
      language: generic
      python: "3.5"

      before_install:
        - sudo apt install pyqt5-dev-tools      

script:
  - exit 0
