# vim: set ts=2 et:

# run xvfb with 32-bit color
# xvfb-run -s '-screen 0 1600x1200x24+32' command_goes_here

matrix:
  include:

    # Python 3 + QT5
    - os: linux
      dist: bionic
      sudo: required
      language: generic
      python: "3.5"
      env:
        - QT=5
      addons:
        apt:
          packages:
            - cmake
            - xvfb
      before_install:
        - apt install python-pip
        - pip3 install -y pyqt=5
        - pip3 install -y lxml
        #- make qt5py3
        #- xvfb-run make testpy3

script:
  - exit 0
